---
- name: Creating ${HOME}/.config directory
  file:
    path: ${HOME}/.config
    state: directory
    mode: '0755'

- name: "Creating directory $HOME/.virtualenvs"
  file:
    path: $HOME/.virtualenvs
    state: directory
    mode: 0700

- name: Installing pip packages
  pip:
    name:
      - virtualenv
      - virtualenvwrapper
      - fuzzywuzzy
    extra_args: --user
  register: pip_install_result

- name: "Content of pip_install_result"
  debug:
    var: pip_install_result

#- name: "Including pass"
#  include: pass.yml