---
- name : Installing command line tools
  shell: xcode-select --install
  ignore_errors: true
  register: cli_out

- debug:
    msg: command line tools is already installed
  when: cli_out.rc == 1

- name: homebrew tap
  homebrew_tap:
    name: "{{ brew_tap }}"
    state: present
  tags:
    - homebrew

- name: homebrew
  homebrew:
    name: "{{ brew_packages }}"
    state: present
  tags:
    - homebrew

- name: homebrew cask
  homebrew_cask:
    name: "{{ brew_cask_packages }}"
    state: present
  tags:
    - homebrew_cask

- name: karabiner configuration
  copy:
    src: karabiner.json
    dest: "{{ lookup('env','HOME') }}/.config/karabiner"

- name: Include alfred task in play
  include: alfred.yml
  tags:
    - alfred

- name: Include yabai task in play
  include: yabai.yml
  tags:
    - yabai