---
- name: "Creating directory $HOME/.virtualenvs"
  file:
    path: $HOME/.virtualenvs
    state: directory
    mode: 0700

- name: Installing pip packages
  pip:
    name: "{{ pip }}"
    extra_args: --user
  register: pip_install_result

- name: "Content of pip_install_result"
  debug:
    var: pip_install_result