---
- name: Installing apt packages
  become: true
  apt:
    update_cache: yes
    pkg: "{{ pkg }}"
  register: aptout

- name: Show content of apt task
  debug: var=aptout

- name: Copying .config directory
  copy:
    src: .config/
    dest: "{{ lookup('env','HOME') }}/.config"
    backup: yes