---
- name: "Copying $HOME/.gnupg/gpg-agent.conf file"
  copy:
    src: "gpg-agent.conf"
    dest: "{{ lookup('env','HOME') }}/.gnupg/"

- name: "Reloading gpg agent"
  shell: gpg-connect-agent reloadagent /bye