---
- hosts: localhost
  remote_user: "{{ remote_user }}"

  vars_files:
    - roles/dotfiles/vars/ubuntu.yml

  roles:
    - {role: color-scheme-terminal, tags: ['color-scheme-terminal']}
    - {role: dotfiles, tags: ['dotfiles', 'base']}
    - {role: i3, tags: ['i3', 'tuning']}
    - {role: jetbrains-toolbox, tags: ['jetbrains-toolbox', 'base']}    
    - {role: rofi, tags: ['rofi', 'tuning']}
    - {role: pkg, tags: ['pkg', 'base']}
    - {role: python, tags: ['python', 'base']}