---
- hosts: localhost
  remote_user: youvann

  vars_files:
    - roles/dotfiles/vars/ubuntu.yml

  roles:
    - role: ubuntu
      tags: os
    - role: common
      tags: common
    - role: dotfiles
      tags: dotfiles